Repository wonjo-oh-my-girl/kdt-oh-my-gpt, pull requests merged in 2023-11, with the labels that each got.

#91 Add : STT 기능 추가
  omg_project/omg_app/omg_app_views/chat_views.py
  omg_project/omg_app/static/css/chat.css
  omg_project/omg_app/static/css/nav.css
  omg_project/omg_app/static/img/mic.svg
  omg_project/omg_app/templates/chat.html
  omg_project/omg_app/templates/index.html
Labels: ✨ Feature, 🎨 Frontend, 📬 Backend

#90 Feature/chat
  omg_project/omg_app/consumers.py
  omg_project/omg_app/omg_app_tests/chat_tests.py
  omg_project/omg_project/asgi.py
Labels: ⚙ Setting, ✅ Test

#105 Feature/chat
  omg_project/omg_app/consumers.py
  omg_project/omg_app/omg_app_views/chat_views.py
Labels: ✨ Feature, 📬 Backend

#108 Feature/payment
  omg_project/omg_app/static/js/logout.js
  omg_project/omg_app/static/js/payment_call.js
  omg_project/omg_app/static/js/usersubscription.js
  omg_project/omg_app/templates/index.html
  omg_project/omg_app/tests.py
  omg_project/omg_app/urls.py
  omg_project/omg_app/views.py
Labels: 🎨 Frontend, 📬 Backend

#115 Fe/form
  omg_project/omg_app/omg_app_views/chat_views.py
  omg_project/omg_app/omg_app_views/user_views.py
  omg_project/omg_app/static/css/chat.css
  omg_project/omg_app/templates/chat.html
  omg_project/omg_app/templates/nav.html
  omg_project/omg_app/views.py
Labels: 🎨 Frontend, 📬 Backend

#114 Feature/chat
  omg_project/omg_app/consumers.py
  omg_project/omg_app/models.py
  omg_project/omg_app/omg_app_urls/chat_urls.py
  omg_project/omg_app/omg_app_urls/model_urls.py
  omg_project/omg_app/omg_app_views/chat_views.py
  omg_project/omg_app/omg_app_views/model_views.py
  omg_project/omg_app/templates/chat.html
  omg_project/omg_app/urls.py
Labels: ✨ Feature, 📬 Backend, 💻Datebase

#118 Feature/chat
  omg_project/omg_app/omg_app_views/chat_views.py
  omg_project/omg_app/static/css/chat.css
  omg_project/omg_app/templates/chat.html
Labels: ✨ Feature, 📬 Backend
