Repository wonjo-oh-my-girl/kdt-oh-my-gpt, pull requests merged in 2023-10, with the labels that each got.

#75 Feature/payment
  omg_project/omg_app/static/js/payment_call.js
  omg_project/omg_app/views.py
  omg_project/omg_project/settings.py
Labels: ✨ Feature, ⚙ Setting, 🔨 Refactor, 📬 Backend

#77 Add : 이메일 인증
  omg_project/omg_app/omg_app_urls/user_urls.py
  omg_project/omg_app/omg_app_views/tokens.py
  omg_project/omg_app/omg_app_views/user_views.py
  omg_project/omg_app/static/css/login.css
  omg_project/omg_app/static/js/login.js
  omg_project/omg_app/templates/account/activation_email.html
  omg_project/omg_app/templates/index.html
  omg_project/omg_app/templates/login.html
  omg_project/omg_app/templates/nav.html
  omg_project/omg_project/settings.py
Labels: ✨ Feature, 📬 Backend

#78 Add : Dockerfile
  Dockerfile
  omg_project/omg_app/static/css/chat.css
  omg_project/omg_app/static/css/index.css
  omg_project/omg_app/static/js/logout.js
  omg_project/omg_app/static/js/payment_call.js
  omg_project/omg_app/templates/chat.html
Labels: 🌏 Deploy

#79 Update : localhost 경로 수정
  omg_project/omg_app/static/js/login.js
Labels: 🌏 Deploy
